export const defaultTools = [
  {
    category: 'tool',
    name: 'hold',
    moduleName: 'Hold',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: 'assets/images/icons/hand.png',
      cursor: 'grab',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      mouseMove: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'undoredo',
    moduleName: 'Undoredo',
    properties: {
      enable: true,
      type: 'own-click',
      toolbar: 'second',
      icon: '/assets/images/icons/reply.png',
      cursor: 'default',
      active: false,
    },
    events: {
      canvasUndo: 'click',
    },
  },
  {
    category: 'tool',
    name: 'undoredo',
    moduleName: 'Undoredo',
    properties: {
      enable: true,
      type: 'own-click',
      toolbar: 'second',
      icon: '/assets/images/icons/redo.png',
      cursor: 'default',
      active: false,
    },
    events: {
      canvasRedo: 'click',
    },
  },
  {
    category: 'tool',
    name: 'zoominout',
    moduleName: 'ZoomInOut',
    properties: {
      enable: true,
      type: 'own-click',
      toolbar: 'second',
      icon: '/assets/images/icons/zoom.png',
      cursor: 'default',
      active: false,
    },
    events: {
      canvasZoomIn: 'click',
    },
  },
  {
    category: 'tool',
    name: 'zoominout',
    moduleName: 'ZoomInOut',
    properties: {
      enable: true,
      type: 'own-click',
      toolbar: 'second',
      icon: '/assets/images/icons/zoom-out.png',
      cursor: 'default',
      active: false,
    },
    events: {
      canvasZoomOut: 'click',
    },
  },
  {
    category: 'tool',
    name: 'viewport',
    moduleName: 'Viewport',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'second',
      icon: '/assets/images/icons/drag.png',
      cursor: 'all-scroll',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      drag: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'layers',
    moduleName: 'Layers',
    properties: {
      enable: true,
      type: 'own-click',
      toolbar: 'second',
      icon: '/assets/images/icons/forward.png',
      cursor: 'default',
      active: false,
    },
    events: {
      elementForward: 'click',
    },
  },
  {
    category: 'tool',
    name: 'layers',
    moduleName: 'Layers',
    properties: {
      enable: true,
      type: 'own-click',
      toolbar: 'second',
      icon: '/assets/images/icons/backward.png',
      cursor: 'default',
      active: false,
    },
    events: {
      elementBackward: 'click',
    },
  },
  {
    category: 'tool',
    name: 'rectangle',
    moduleName: 'Rectangle',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: '/assets/images/icons/rectangle.png',
      cursor: 'crosshair',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      mouseMove: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'line',
    moduleName: 'Line',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: '/assets/images/icons/line.png',
      cursor: 'crosshair',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      mouseMove: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'circle',
    moduleName: 'Circle',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: '/assets/images/icons/ellipse.png',
      cursor: 'crosshair',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      mouseMove: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'triangle',
    moduleName: 'Triangle',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: '/assets/images/icons/triangle.png',
      cursor: 'crosshair',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      mouseMove: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'curvedrectangle',
    moduleName: 'Curvedrectangle',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: '/assets/images/icons/minus.png',
      cursor: 'crosshair',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
      mouseMove: 'mousemove',
      mouseUp: 'mouseup',
    },
  },
  {
    category: 'tool',
    name: 'text',
    moduleName: 'Text',
    properties: {
      enable: true,
      type: 'canvas-tool',
      toolbar: 'main',
      icon: '/assets/images/icons/font.png',
      cursor: 'crosshair',
      active: false,
    },
    events: {
      mouseDown: 'mousedown',
    },
  },
];

// TODO add variable of tool ordering
